/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A decimal representation of a number. */
export declare class Decimal {
  numOfDecimals: number
  signature: Signature
  digits: Array<number>
  /**
   * Creates a new decimal number.
   *
   * # Return
   * This function returns null if number is not valid.
   */
  static new(number: string): Decimal | null
}

/** Signature enum that represents the sign of a number. */
export declare const enum Signature {
  Positive = 'Positive',
  Negative = 'Negative',
  Zero = 'Zero'
}
