/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Decimal {
  numOfDecimals: number
  signature: Signature
  digits: Array<number>
  static new(number: string): Decimal | null
}

export declare const enum Signature {
  Positive = 'Positive',
  Negative = 'Negative',
  Zero = 'Zero'
}
